#ifndef WORKFLOW_CONSTANTS_H
#define WORKFLOW_CONSTANTS_H

#define PROGRAM_STOP 1
#define SMALL_COUNT_ARGS 2
#define COUNT_ARGS 3
#define BIG_COUNT_ARGS 5
#define NAME_POSITION 1
#define NEXT_NAME_POSITION 2
#define START_POSITION 0


#endif //WORKFLOW_CONSTANTS_H
