#ifndef CLAB1_CONSTS_H
#define CLAB1_CONSTS_H

#define INITIAL_COUNT 0
#define INITIAL_INDEX -1
#define EMPTY_MEMORY 0
#define COUNT_TRIT_IN_BIT 2
#define BYTE_IN_UINT 32
#define ADDITIONAL_MEMORY 1
#define ADDITIONAL_INDEX 1

#endif //CLAB1_CONSTS_H
